### ISSUE TITLE
建议加个静态方法

### ISSUE THREAD

**Issue by abigsoft** [workbunny/webman-ip-attribution#1]
对于只加载一次的方法，每次实例化一次太麻烦了，能加个静态方法吗？

**Comment by chaz6chez** [comment]
webman有容器管理，其实建议可以使用容器管理的长生命周期达到静态使用的效果；

```php
/** @var Location $location */
$location = Container::get(Location::class);
```

当然要加一个静态instance()方法用来简单静态化也可以，但本着复用webman生态及静态对象管理的心态，就没有滥用静态变量。
